### ISSUE TITLE
Aard_Clock running 5 days behind aard time

### ISSUE THREAD

**Issue by Shindo-Aardwolf** [AardCrowley/Aardwolf-Scripts#3]
Just saw the next season tick over

\#\# Aardwolf moves into the Season of the River. \#\#

  \*  It is Noon on the 1st day of the Season of the River, year 12 AVT.

  \*  It is the year of the Marauder.

but the clock is 5 days behind on Season of scourge

**Comment by AardCrowley** [comment]
Fixed! Just type 'aardclock update' to update to the newest version. Thank you!
