### ISSUE TITLE
No obvious way to turn off Aardwolf Clock plugin other than disabling or removing the plugin

### ISSUE THREAD

**Issue by danj2k** [AardCrowley/Aardwolf-Scripts#6]
The Aardwolf Clock plugin doesn't currently appear to have any obvious way to turn the clock off or hide the window when it's not being used, other than disabling or removing the plugin.

Because of the speed of the hand movement it can be very distracting to have on screen when I'm not in an area that's depending on game time.

**Comment by KnittedKharpern** [comment]
Danj: you can right click and send to back

It is also very big and it would be nice if it was more compact for someone with a smaller screen. I personally don't need a huge clock face, maybe an option to make it more compact.

**Comment by AardCrowley** [comment]
Added:

aardclock (show|on) - shows the clock
aardclock (hide|off) - hides the clock

**Comment by AardCrowley** [comment]
Do 'aardclock update' to update to the latest version.
